### ISSUE TITLE
Create Users Stories

### ISSUE THREAD

**Issue by JoeDLehmanJr** [JoeDLehmanJr/Fall-2022-CPW221-Project-eCom#19]
Add to README.
In the pattern of
As a {stakeholder/role} I want to {perform some action} so that {get a benefit}:

- [x] #20 
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26

**Comment by jwestphalen** [comment]
Completed User Stories Earlier and added to README. Closing meta issue and related issues
